# Config file for automatic testing at travis-ci.com

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script: poetry run pytest
after_success: codecov

stages:
  - test
  - lint
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
- provider: script
  script: poetry publish --build
  on:
    python: 3.8
    branch: master
    tags: true

# end
