# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: UKYOL4bDT6siJiVo0QtJQd0GifvobpIwFI2y8xR3KOJjTE0OjNt+/uSOyAJT2YL+xh7zE5wOQGm5aYKCksR9AWP7oTdY/3P9ipsjlMjVGpd18sIXtSNF8vW5SeJhV+8yXcZwi7A4l4ewAxf/+9c18wHOmRjr3Qu81apU3nVT3hlB/l0yGR1k5gP4OauOxyR86D1mXM1xeIZPvWPxpgZcdZpCDIaW9klDp2mMRQw12+T5s1d7aFEDa4/hIG9VRpLc4E2nO2us2JI041K6EvnfQIGzaGWoACGD5Z/9O4kBetMTBoRnRFBiDscwCIfVMV479NIsB9A0g8X8Bo5aB780nb+MxG40vdmR6yqcVW/eKQji++utluAPdNJ8Sz0wwgWKCkc+pG7nHKPeIJL6d74IKz4O9tZBONzRYed+8Ji/4ZM4ov5VnXnR8aC35Z9W5JjiOh9IpSuPTFblP8uZuI3VcWZrCuyUemlxNf+RKzif5H0Cc4BsUEDHFaD6pIiuNL5IUiuVQ6brX5AjoCgH1UBxvqriE5jNLgQwGuT/zZLcyrSZ7+AuGOmbjAqbUaIErWe3h7oYymXGP8F79ECrKYbMUAPsoxY8YcK26bEAMbZdfJ9uoLSzkNwNERS1fVDm5F8Cdp9zank0pPLy5g2Zc292Z7szLE907Qr5V6bs9TpAVoI=
  on:
    tags: true
    repo: nigelm/ssh2_parse_key
    python: 3.8

# end
